### ISSUE TITLE
Akka.Cluster.Bootstrap critical failure

### ISSUE THREAD

**Issue by Aaronontheweb** [akkadotnet/Akka.Management#1197]
**Version Information**
Version of Akka.NET? v1.0.0-beta2
Which Akka.NET Modules? Akka.Discovery.K8s, Akka.Management

**Describe the bug**

When booting with the following configuration:

```csharp
// Add Akka.Management support
builder.WithAkkaManagement(setup =>
{
    setup.Http.Port = options.AkkaClusterOptions.ManagementPort;
});

// Add Akka.Management.Cluster.Bootstrap support
builder.WithClusterBootstrap(setup =>
{
    setup.ContactPointDiscovery.PortName = "management";
    setup.ContactPointDiscovery.RequiredContactPointsNr = 3;
}, autoStart: true);

// Add Akka.Discovery.KubernetesApi support
builder.WithKubernetesDiscovery(c =>
{
    c.PodNamespace = options.AkkaClusterOptions.KubernetesDiscoveryOptions.PodNamespace;
    c.PodLabelSelector = options.AkkaClusterOptions.KubernetesDiscoveryOptions.PodLabelSelector;
});
```

We get the following exception:

```
ERROR][01/07/2023 15:11:04][Thread 0005][ClusterBootstrap (akka://LargeNetworkSys)] Failed to autostart cluster bootstrap, terminating system
Cause: System.ArgumentException: Could not load discovery config from path [akka.discovery.kubernetes-api]
   at Akka.Discovery.Discovery.CreateServiceDiscovery(String method)
   at Akka.Discovery.Discovery.<>c__DisplayClass7_0.<LoadServiceDiscovery>b__0()
   at System.Lazy`1.ViaFactory(LazyThreadSafetyMode mode)
   at System.Lazy`1.ExecutionAndPublication(LazyHelper executionAndPublication, Boolean useDefaultConstructor)
   at System.Lazy`1.CreateValue()
   at System.Lazy`1.get_Value()
   at Akka.Discovery.Discovery.LoadServiceDiscovery(String method)
   at Akka.Discovery.Discovery.<>c__DisplayClass4_1.<.ctor>b__1()
   at System.Lazy`1.ViaFactory(LazyThreadSafetyMode mode)
   at System.Lazy`1.ExecutionAndPublication(LazyHelper executionAndPublication, Boolean useDefaultConstructor)
   at System.Lazy`1.CreateValue()
   at System.Lazy`1.get_Value()
   at Akka.Discovery.Discovery.get_Default()
   at Akka.Management.Cluster.Bootstrap.ClusterBootstrap.<>c__DisplayClass16_0.<.ctor>b__0()
   at System.Lazy`1.ViaFactory(LazyThreadSafetyMode mode)
   at System.Lazy`1.ExecutionAndPublication(LazyHelper executionAndPublication, Boolean useDefaultConstructor)
   at System.Lazy`1.CreateValue()
   at System.Lazy`1.get_Value()
   at Akka.Management.Cluster.Bootstrap.ClusterBootstrap.Start()
   at Akka.Management.Cluster.Bootstrap.ClusterBootstrap.<>c__DisplayClass16_0.<<-ctor>b__2>d.MoveNext()
[INFO][01/07/2023 15:11:04][Thread 0020][remoting-terminator] Shutting down remote daemon.
[INFO][01/07/2023 15:11:04][Thread 0020][remoting-terminator] Remote daemon shut down; proceeding with flushing remote transports.
[ERROR][01/07/2023 15:11:04][Thread 0015][akka://LargeNetworkSys/system/sharding/itemsCoordinator] Cluster node must not be terminated
Cause: [akka://LargeNetworkSys/system/sharding/itemsCoordinator#402890287]: Akka.Actor.ActorInitializationException: Exception during creation
 ---> Akka.Actor.ActorInitializationException: Cluster node must not be terminated
   at Akka.Cluster.Tools.Singleton.ClusterSingletonManager.PreStart()
   at Akka.Actor.ActorBase.AroundPreStart()
   at Akka.Actor.ActorCell.<>c__DisplayClass176_0.<Create>b__0()
   at Akka.Actor.ActorCell.UseThreadContext(Action action)
   at Akka.Actor.ActorCell.Create(Exception failure)
   --- End of inner exception stack trace ---
   at Akka.Actor.ActorCell.Create(Exception failure)
   at Akka.Actor.ActorCell.SysMsgInvokeAll(EarliestFirstSystemMessageList messages, Int32 currentState)
```

**Reproduction**

https://github.com/petabridge/AkkaDotNet.LargeNetworkTests/pull/73

**Expected behavior**

The system should boot without any issues.

**Actual behavior**

Clustering plugin kills itself.

**Additional context**

I'm more or less using the code straight out of https://github.com/akkadotnet/Akka.Management/blob/dev/src/management/Akka.Management/README.md#setting-up-clusterbootstrap-using-akkahosting -- which btw, those code samples should also include the required call to `WithAkkaManagement` .

**Comment by Aaronontheweb** [comment]
Worked around this issue via the following:

```csharp
 // Add Akka.Discovery.KubernetesApi support
            builder.WithKubernetesDiscovery(c =>
            {
                c.PodNamespace = options.AkkaClusterOptions.KubernetesDiscoveryOptions.PodNamespace;
                c.PodLabelSelector = options.AkkaClusterOptions.KubernetesDiscoveryOptions.PodLabelSelector;
            });

            builder.AddHocon(
                @"akka.discovery.kubernetes-api.class = ""Akka.Discovery.KubernetesApi.KubernetesApiServiceDiscovery, Akka.Discovery.KubernetesApi""", HoconAddMode.Prepend);
```

But still received fatal errors - here's what I ran into:

```
[ERROR][01/07/2023 15:23:17][Thread 0016][ClusterBootstrap (akka://LargeNetworkSys)] Failed to autostart cluster bootstrap, terminating system
Cause: System.InvalidOperationException: Cannot create child while terminating or terminated
   at Akka.Actor.ActorCell.MakeChild(Props props, String name, Boolean async, Boolean systemService)
   at Akka.Actor.ActorCell.AttachChild(Props props, Boolean isSystemService, String name)
   at Akka.Actor.Internal.ActorSystemImpl.SystemActorOf(Props props, String name)
   at Akka.Management.Cluster.Bootstrap.ClusterBootstrap.Start()
   at Akka.Management.Cluster.Bootstrap.ClusterBootstrap.<>c__DisplayClass16_0.<<-ctor>b__2>d.MoveNext()
```

I've attached full logs here, but it seems like we need some more "end to end" testing with the Akka.Management + Discovery APIs as these are all "config not found" errors.

[dump.txt](https://github.com/akkadotnet/Akka.Management/files/10366599/dump.txt)

**Comment by Aaronontheweb** [comment]
Looks like the issues I'm running into now are due to the configuration of Akka.Coordination.Kubernetes - I haven't migrated that config to the latest yet.

**Comment by Arkatufus** [comment]
Should be fixed with the latest version, your code should be compatible with the new API

**Comment by Aaronontheweb** [comment]
This has been resolved.
