### ISSUE TITLE
Akka.Coordination.Kubernetes crash on startup

### ISSUE THREAD

**Issue by Aaronontheweb** [akkadotnet/Akka.Management#1198]
**Version Information**
Version of Akka.NET? 1.0.0-beta2
Which Akka.NET Modules? Akka.Coordination.Kubernetes

**Describe the bug**

When I start up my application with the following configuration:

```csharp
if (options.AkkaClusterOptions.UseKubernetesLease)
{
    clusterOptions.SplitBrainResolver = new LeaseMajorityOption()
    {
        LeaseImplementation = new KubernetesLeaseOption()
        {

        }
    };
}
```

I get the following exception:

```
 ---> System.NullReferenceException: Object reference not set to an instance of an object.
   at Akka.Coordination.LeaseProvider.<>c__DisplayClass9_0.<GetLease>b__0(LeaseKey lk)
   at System.Collections.Concurrent.ConcurrentDictionary`2.GetOrAdd(TKey key, Func`2 valueFactory)
   at Akka.Coordination.LeaseProvider.GetLease(String leaseName, String configPath, String ownerName)
   at Akka.Cluster.SBR.SplitBrainResolverProvider.get_DowningActorProps()
   at Akka.Cluster.ClusterCoreDaemon.PreStart()
   at Akka.Actor.ActorBase.AroundPreStart()
   at Akka.Actor.ActorCell.<>c__DisplayClass176_0.<Create>b__0()
   at Akka.Actor.ActorCell.UseThreadContext(Action action)
   at Akka.Actor.ActorCell.Create(Exception failure)
   --- End of inner exception stack trace ---
   at Akka.Actor.ActorCell.Create(Exception failure)
   at Akka.Actor.ActorCell.SysMsgInvokeAll(EarliestFirstSystemMessageList messages, Int32 currentState)] - shutting down...
Cause: [akka://LargeNetworkSys/system/cluster/core/daemon#1418493974]: Akka.Actor.ActorInitializationException: Exception during creation
 ---> System.NullReferenceException: Object reference not set to an instance of an object.
   at Akka.Coordination.LeaseProvider.<>c__DisplayClass9_0.<GetLease>b__0(LeaseKey lk)
   at System.Collections.Concurrent.ConcurrentDictionary`2.GetOrAdd(TKey key, Func`2 valueFactory)
   at Akka.Coordination.LeaseProvider.GetLease(String leaseName, String configPath, String ownerName)
   at Akka.Cluster.SBR.SplitBrainResolverProvider.get_DowningActorProps()
   at Akka.Cluster.ClusterCoreDaemon.PreStart()
   at Akka.Actor.ActorBase.AroundPreStart()
   at Akka.Actor.ActorCell.<>c__DisplayClass176_0.<Create>b__0()
   at Akka.Actor.ActorCell.UseThreadContext(Action action)
   at Akka.Actor.ActorCell.Create(Exception failure)
   --- End of inner exception stack trace ---
   at Akka.Actor.ActorCell.Create(Exception failure)
```

**Expected behavior**

Application should start up correctly using reasonable defaults.

**Actual behavior**

Application crashes during Akka.Cluster launch.

**Additional context**

If there are any required properties, Akka.Hosting should either use a reasonable default or force me to specify them.

**Comment by Aaronontheweb** [comment]
Full code from this application can be found here: https://github.com/petabridge/AkkaDotNet.LargeNetworkTests/pull/73

**Comment by Arkatufus** [comment]
Have you actually added kubernetes lease to the builder?
```csharp
if (options.AkkaClusterOptions.UseKubernetesLease)
{
    var leaseOption = new KubernetesLeaseOption { }; // set lease options in here
    builder.WithKubernetesLease(leaseOption);
    clusterOptions.SplitBrainResolver = new LeaseMajorityOption()
    {
        LeaseImplementation = leaseOption
    };
}
```

**Comment by Aaronontheweb** [comment]
oh, no I have not - didn't realize I need to do both of those

**Comment by Aaronontheweb** [comment]
This has been resolved.
