### ISSUE TITLE
Akka.Discovery.KubernetesApi - need to document how to set up RBAC roles while enabled

### ISSUE THREAD

**Issue by Aaronontheweb** [akkadotnet/Akka.Management#517]
**Please describe what you are trying to understand**

Docker Desktop v4.3.0 closed a security hole in their local K8s instances that caused RBAC rules to not be enforced https://www.portainer.io/blog/docker-desktop-kubernetes-not-enforcing-rbac-rules - previously this allowed Akka.Discovery.KubernetesApi to "just work" out of the box without having to assign a custom service account to it or give it any special permissions.

Now when you run Akka.Discovery.KubernetesApi by default you will receive the following exception from K8s:

```
Microsoft.Rest.HttpOperationException: Operation returned an invalid status code 'Forbidden'
   at k8s.Kubernetes.ListNamespacedPodWithHttpMessagesAsync(String namespaceParameter, Nullable`1 allowWatchBookmarks, String continueParameter, String fieldSelector, String labelSelector, Nullable`1 limit, String resourceVersion, String resourceVersionMatch, Nullable`1 timeoutSeconds, Nullable`1 watch, String pretty, Dictionary`2 customHeaders, CancellationToken cancellationToken)
   at Akka.Discovery.KubernetesApi.KubernetesApiServiceDiscovery.Lookup(Lookup lookup, TimeSpan resolveTimeout)

[AkkaDotNet.BackEnd][backend-0][16:07:07 Warning] Akka.Management.Cluster.Bootstrap.Internal.BootstrapCoordinator
Resolve attempt failed! Cause: k8s.KubernetesException: Forbidden when communicating with the Kubernetes API. Check RBAC settings.
 ---> Microsoft.Rest.HttpOperationException: Operation returned an invalid status code 'Forbidden'
   at k8s.Kubernetes.ListNamespacedPodWithHttpMessagesAsync(String namespaceParameter, Nullable`1 allowWatchBookmarks, String continueParameter, String fieldSelector, String labelSelector, Nullable`1 limit, String resourceVersion, String resourceVersionMatch, Nullable`1 timeoutSeconds, Nullable`1 watch, String pretty, Dictionary`2 customHeaders, CancellationToken cancellationToken)
   at Akka.Discovery.KubernetesApi.KubernetesApiServiceDiscovery.Lookup(Lookup lookup, TimeSpan resolveTimeout)
   --- End of inner exception stack trace ---
   at Akka.Discovery.KubernetesApi.KubernetesApiServiceDiscovery.Lookup(Lookup lookup, TimeSpan resolveTimeout)
   at Akka.Actor.PipeToSupport.PipeTo[T](Task`1 taskToPipe, ICanTell recipient, Boolean useConfigureAwait, IActorRef sender, Func`2 success, Func`2 failure)
k8s.KubernetesException: Forbidden when communicating with the Kubernetes API. Check RBAC settings.
```

There's nothing we can do to fix that automagically from our side - but we should document how users can work around this issue by changing the service account permissions.

**Which pages have you looked at?**

The JVM Akka.Discovery literature explains how to solve this issue: https://doc.akka.io/docs/akka-management/current/discovery/kubernetes.html

**What did these pages not make clear?**

We need to provide the YAML that users can use to fix and mitigate this issue themselves.

**Comment by Aaronontheweb** [comment]
Completed as part of @Arkatufus other documentation PRs.
